services:
  db:
    container_name: postgresql_container
    image: postgres:14.10
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_USERNAME}
      - POSTGRES_USER=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql@14/data
    restart: always
  backend:
    build: .
    image: ghcr.io/stickydice/midas-server-ghcr
    container_name: server_container
    ports:
      - 8181:8181
    env_file:
      - .env
    environment:
      - spring.datasource.url=${DB_URL}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
      - spring.datasource.hikari.minimumIdle = 2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    restart: always